AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
Lint/HandleExceptions:
  Exclude:
    - test/test_helper.rb
Metrics/MethodLength:
  Max: 13
Naming/FileName:
  Enabled: false
Style/Documentation:
  Enabled: false
