language: ruby
before_install:
  - gem update --system
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9000
  - ruby-head
bundler_args: --without development
sudo: false
